### ISSUE TITLE
Where to find libimplicit?

### ISSUE THREAD

**Issue by non-void** [etcwilde/MarchingTriangles#1]
Hello etcwilde, I want to complie and run your code, however I can't find the libimplicit mentioned in your readme.md. Can you provide it?

**Comment by etcwilde** [comment]
Hi non-void, 
You can find my implicit system here: https://github.com/etcwilde/ImplicitSystem
I didn't actually get the marching triangles algorithm to work and the implementation is incomplete, but it is a start. I've also implemented Marching Cubes, which does work and generates meshes.
